### ISSUE TITLE
Routes Resolving before data promises

### ISSUE THREAD

**Issue by hassanbazzi** [scttcper/honbot-client#2]
![screen shot 2015-06-12 at 3 25 26 pm](https://cloud.githubusercontent.com/assets/3339608/8141105/4a4ae378-1117-11e5-9ed6-61604fc1a265.png)

Tables for matches, heroes, and items are showing without the data. A loading stage is probably needed.  This is something I can work on if you have nothing implemented already.

Let me know ;)

**Comment by scttcper** [comment]
Probably needs a loading spinner or something. I'm fine with the route changing as depending on the player it could be downloading several mb. People would think it wasn't working.

**Comment by hassanbazzi** [comment]
Yea exactly. Just a loader basically. We can just implement this in the router layer. Make a spinner that works when routes are changing and if there's a resolve parameter, then wait for that promise to resolve.

**Comment by hassanbazzi** [comment]
@scttcper I see the spinners on the site now. Mark this as solved I guess?
