### ISSUE TITLE
Navbar broken iOS 8 chrome

### ISSUE THREAD

**Issue by scttcper** [scttcper/honbot-client#5]
![2015-06-14 00 46 14](https://cloud.githubusercontent.com/assets/1400464/8147719/16edb1fe-122f-11e5-87de-15ecb8bf3d79.png)

Needs help. I'd like the search bar to be visible when in mobile. The dropdown for bookmarks flows underneath the next div which is horribly wrong. This could be an angular-strap issue.

**Comment by hassanbazzi** [comment]
I'll look into this one

**Comment by hassanbazzi** [comment]
Aaaaand I'm back. Long vacation :D.  Will be getting these done.

**Comment by hassanbazzi** [comment]
Not sure if you fixed this, but do we even have a navbar? What are the nav items?

**Comment by scttcper** [comment]
There's just the one navbar item right now seen after clicking the star next to a players name.

**Comment by hassanbazzi** [comment]
I see. I lied btw, won't be available again. haha. 

I just joined a new startup and settling in for a bit. Awesome job with all the stuff you're doing dude.

**Comment by scttcper** [comment]
Cool beans.
